name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install dependencies and run tests
        run: npm test
      - name: Generate reports
        run: npm run report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report.html
          path: allure-report/complete.html
          retention-days: 30